version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
    - checkout
    #- run: npm install
    #- run: npm run lint

  test:
    docker:
      - image: microsoft/azure-cli

    working_directory: ~/repo

    steps:
      - checkout
      #- run: az --version
      #- run: az login -u daniel.moreira@present-technologies.com -p Present6?
      #- run: cd ~/repo/src
      - run: ls -al ~/repo/src
      - run: ~/repo/scripts/test.sh

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - test



